# Generated by Django 5.1.5 on 2026-07-31 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, default='', max_length=96)),
                ('qualifications', models.CharField(blank=True, default='', max_length=160)),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('working_hours', models.JSONField(blank=True, default=list)),
                ('slot_minutes', models.IntegerField(default=30)),
                ('booking_horizon_days', models.IntegerField(default=30)),
                ('default_meeting_link', models.URLField(blank=True, default='')),
            ],
            options={
                'db_table': 'clinician_profiles',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('clinician', 'scheduled_for'), name='uniq_clinician_slot_active'),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
