# Generated by Django 5.1.5 on 2026-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clinicianprofile_appointment_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianprofile',
            name='accepting_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinicianprofile',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
