# Generated by Django 5.1.5 on 2026-08-01 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clinicianprofile_accepting_patients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_key', models.CharField(max_length=48)),
                ('on_date', models.DateField(db_index=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('minutes', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehab_activities', to='api.patient')),
            ],
            options={
                'db_table': 'rehab_activity_log',
                'ordering': ['-on_date', '-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'activity_key', 'on_date'), name='uniq_rehab_activity_per_day')],
            },
        ),
    ]
