# Generated by Django 5.1.5 on 2026-08-01 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rehabactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='masking_thresholds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assessment',
            name='masking_unmasked_hz',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reference_level_db',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reference_level_hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateField(db_index=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tinnitus_loudness', models.FloatField(blank=True, null=True)),
                ('tinnitus_annoyance', models.FloatField(blank=True, null=True)),
                ('sleep_quality', models.FloatField(blank=True, null=True)),
                ('stress_level', models.FloatField(blank=True, null=True)),
                ('mood', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='api.patient')),
            ],
            options={
                'db_table': 'daily_check_ins',
                'ordering': ['-on_date'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'on_date'), name='uniq_checkin_per_day')],
            },
        ),
    ]
