# Generated by Django 5.1.5 on 2026-08-20 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_communitypost_likes_user_joined_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('meet_url', models.URLField(blank=True, default='', max_length=500)),
                ('invite_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('max_participants', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=16)),
                ('current_activity', models.CharField(choices=[('breathing', 'Breathing & Soundscape'), ('mood_checkin', 'Mood & Distress Check-in'), ('reflection_prompt', 'Reflection Prompt'), ('gratitude_wall', 'Gratitude Wall')], default='breathing', max_length=32)),
                ('activity_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_group_sessions', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_group_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_therapy_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupTherapyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('emoji_reaction', models.CharField(blank=True, default='', max_length=20)),
                ('message_type', models.CharField(choices=[('chat', 'Chat'), ('feeling_emoji', 'Feeling Emoji'), ('system', 'System')], default='chat', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_therapy_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.grouptherapysession')),
            ],
            options={
                'db_table': 'group_therapy_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupTherapyActivityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(db_index=True, max_length=32)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_activity_responses', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_responses', to='api.grouptherapysession')),
            ],
            options={
                'db_table': 'group_therapy_activity_responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
