# Generated by Django 5.1.5 on 2026-08-20 09:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_grouptherapysession_grouptherapymessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTherapyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.grouptherapysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_therapy_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_therapy_join_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
