# Generated by Django 5.1.5 on 2026-08-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appointment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='audiometry_catch_trials',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='audiometry_false_positives',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='audiometry_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='audiometry_reliable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='audiometry_retest_agreement_db',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
