# Generated by Django 5.1.5 on 2026-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_assessment_audiometry_catch_trials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tinnitus_characters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
