# Generated by Django 5.1.5 on 2026-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_patient_tinnitus_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='mml_masker_hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_reported_category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
