# Generated by Django 5.1.5 on 2026-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_assessment_mml_masker_hz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='about_you',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
