# Generated by Django 5.1.5 on 2026-09-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_patient_about_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='questionnaire_status',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
