# Generated by Django 5.1.5 on 2026-09-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_assessment_questionnaire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_comfort_level_db',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_confirmation',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_initial_level_db',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_not_sure_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_octave_frequency_hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_octave_response',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_sound_description',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pitch_match_sound_other_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
