# Generated by Django 5.1.5 on 2026-09-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pitch_match_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='loudness_match_confirmation',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='assessment',
            name='loudness_match_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='loudness_match_starting_level_db',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='loudness_match_trace',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
