# Generated by Django 5.1.5 on 2026-09-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_loudness_match_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='masking_not_sure_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='masking_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='masking_trace',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
