# Generated by Django 5.1.5 on 2026-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_masking_curve_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='ldl_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ldl_trace',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_baseline_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_immediate_response',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_monitoring',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_post_stimulation_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_reduction_detected_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_repeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_return_to_baseline_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_stimulation_duration_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_stimulation_started_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_stimulation_stopped_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_stimulus_frequency_hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ri_stimulus_level_db',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
