# Generated by Django 5.1.5 on 2026-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_ri_ldl_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='tfi_items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
