# Generated by Django 5.1.5 on 2026-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_tfi_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='isi_items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
