# Generated by Django 5.1.5 on 2026-09-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_isi_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='phq9_functional_difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='phq9_items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
